INSERT INTO ROLE(nome) VALUES ('ADMIN');
INSERT INTO ROLE(nome) VALUES ('USER');

INSERT INTO USUARIO(email,nome,status,password) VALUES ('administrador@acme.com', 'Patolino',1 , '123456');
INSERT INTO USUARIO(email,nome,status,password) VALUES ('exfuncionario@acme.com', 'Eufrasino',2 , '123456');

INSERT INTO USUARIO_ROLES(ROLES_ID, USUARIO_ID) VALUES (1,1);
INSERT INTO USUARIO_ROLES(ROLES_ID, USUARIO_ID) VALUES (2,1);
INSERT INTO USUARIO_ROLES(ROLES_ID, USUARIO_ID) VALUES (2,2);

INSERT INTO PRODUTO(CODIGO, NOME, VALOR) VALUES (1L, 'Hamburguer', 30);
INSERT INTO PRODUTO(CODIGO, NOME, VALOR) VALUES (2L, 'Coca-Cola', 10);
INSERT INTO PRODUTO(CODIGO, NOME, VALOR) VALUES (3L, 'Pudim', 16);
INSERT INTO PRODUTO(CODIGO, NOME, VALOR) VALUES (4L, 'Pepsi', 8);
INSERT INTO PRODUTO(CODIGO, NOME, VALOR) VALUES (5L, 'Pavê', 12);
INSERT INTO PRODUTO(CODIGO, NOME, VALOR) VALUES (6L, 'Pizza Calabresa', 70);
INSERT INTO PRODUTO(CODIGO, NOME, VALOR) VALUES (7L, 'Crepe - Queijo e Presunto', 10);
INSERT INTO PRODUTO(CODIGO, NOME, VALOR) VALUES (8L, 'Mini-Torta', 15);

INSERT INTO BEBIDA(CODIGO, MARCA, TAMANHO, GELADA) VALUES (2L, 'Coca-Cola', 10, TRUE);
INSERT INTO BEBIDA(CODIGO, MARCA, TAMANHO, GELADA) VALUES (4L, 'Pepsi', 10, FALSE);

INSERT INTO COMIDA(CODIGO, INGREDIENTES, PESO, VEGANO) VALUES (1L, 'Pão - 1 Hamburguer - Alface - Tomate - Cebola - 1 Quejo - Ovo', 10, FALSE);
INSERT INTO COMIDA(CODIGO, INGREDIENTES, PESO, VEGANO) VALUES (6L, 'Massa - Queijo - Molho de Tomate - Calabresa', 30, FALSE);
INSERT INTO COMIDA(CODIGO, INGREDIENTES, PESO, VEGANO) VALUES (7L, 'Massa - Queijo - Presunto', 30, FALSE);

INSERT INTO SOBREMESA(CODIGO, INFORMACAO, QUANTIDADE, DOCE) VALUES (3L, 'Muito bom', 10, TRUE);
INSERT INTO SOBREMESA(CODIGO, INFORMACAO, QUANTIDADE, DOCE) VALUES (5L, 'Validade expira amanhã', 20, TRUE);
INSERT INTO SOBREMESA(CODIGO, INFORMACAO, QUANTIDADE, DOCE) VALUES (8L, 'Melhor que tem', 100, TRUE);