INSERT INTO ROLE(nome) VALUES ('ADMIN');
INSERT INTO ROLE(nome) VALUES ('USER');

INSERT INTO USUARIO(email,nome,status,password) VALUES ('luiz@gmail.com', 'Luiz',1 , '123456');
INSERT INTO USUARIO(email,nome,status,password) VALUES ('matheus@gmail.com', 'Matheus',2 , '123456');

INSERT INTO PRODUTO(nome,valor) VALUES ('Produto 1', 10L)
INSERT INTO BEBIDA(codigo,nome,valor,gelada,tamanho,marca) VALUES (1L,'HEINEKEN','30','TRUE','HOLANDESA')


INSERT INTO USUARIO_ROLES(ROLES_ID, USUARIO_ID) VALUES (1,1);
INSERT INTO USUARIO_ROLES(ROLES_ID, USUARIO_ID) VALUES (2,1);
INSERT INTO USUARIO_ROLES(ROLES_ID, USUARIO_ID) VALUES (2,2);